apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mikulskisp@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cloudflare
    solvers:
    - dns01:
        cloudflare:
          email: mikulskisp@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
